USE `commune-app`;

ALTER TABLE reports
  MODIFY COLUMN id VARCHAR(36) NOT NULL,
  MODIFY COLUMN title VARCHAR(255) NOT NULL,
  MODIFY COLUMN description TEXT NOT NULL,
  MODIFY COLUMN photo_path TEXT NULL,
  MODIFY COLUMN latitude DOUBLE NULL,
  MODIFY COLUMN longitude DOUBLE NULL,
  MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_reports_created_at ON reports (created_at);
